# Generated by Django 5.2.3 on 2025-06-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='uz_description',
        ),
        migrations.AddField(
            model_name='product',
            name='ru_description',
            field=models.TextField(default='нет'),
        ),
    ]
